spring:
  profiles:
    active: 
    - dev
---
spring:
  profiles: dev   #开发环境
  application:
    name: weather-config-dev
---
spring:
  profiles: test   #开发环境
  application:
    name: weather-config-test
#   注意请保存为UTF-8格式