spring:
  profiles:
    active: 
    - dev
---
server:
  port: 7202
spring:
  profiles: dev
  application: config-server   # 服务名
eureka:
  instance:
    hostname: localhost # eureka服务端的实例名称，可以通过host文件配置域名
  client:
    register-with-eureka: false     # false表示不向注册中心注册自己。
    fetch-registry: false     # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7201/eureka/       # 设置与Eureka Server集群地址，更多集群通过 ,号隔开，集群时不用配置自己地址
---
server:
  port: 7302
spring:
  profiles: test
  application: config-server   # 服务名
eureka:
  instance:
    hostname: localhost # eureka服务端的实例名称，可以通过host文件配置域名
  client:
    register-with-eureka: false     # false表示不向注册中心注册自己。
    fetch-registry: false     # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7301/eureka/       # 设置与Eureka Server集群地址，更多集群通过 ,号隔开，集群时不用配置自己地址
