spring:
  profiles:
    active: 
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: weather-collection-server
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://eureka7201.com:7201/eureka/,http://eureka7202.com:7202/eureka/,http://eureka7205.com:7205/eureka/
  instance:
    instance-id: weather-collection-server-${server.port}
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true
---
server:
  port: 8201
spring:
  profiles: test
  application:
    name: weather-collection-server
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://eureka7201.com:7201/eureka/,http://eureka7202.com:7202/eureka/,http://eureka7205.com:7205/eureka/
  instance:
    instance-id: weather-collection-server-${server.port}
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true

